// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrgCNOa9jh5LIfOJepEilIvuvYEMKaLWQ',
    appId: '1:1098462697075:web:3079d88b16a9e0fc0a3c06',
    messagingSenderId: '1098462697075',
    projectId: 'kot-pos-app',
    authDomain: 'kot-pos-app.firebaseapp.com',
    storageBucket: 'kot-pos-app.firebasestorage.app',
    measurementId: 'G-FGM6TBY2PT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQrQXqjqLEmmvF-m_MDJo312MnXQKGAtY',
    appId: '1:1098462697075:android:1485ba813208cec40a3c06',
    messagingSenderId: '1098462697075',
    projectId: 'kot-pos-app',
    storageBucket: 'kot-pos-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBDCE96lYS_o8gOIgwdQ3tkUQ4iptHyQ8',
    appId: '1:1098462697075:ios:e09cfffe6cdc6b660a3c06',
    messagingSenderId: '1098462697075',
    projectId: 'kot-pos-app',
    storageBucket: 'kot-pos-app.firebasestorage.app',
    iosBundleId: 'com.example.kotApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBDCE96lYS_o8gOIgwdQ3tkUQ4iptHyQ8',
    appId: '1:1098462697075:ios:e09cfffe6cdc6b660a3c06',
    messagingSenderId: '1098462697075',
    projectId: 'kot-pos-app',
    storageBucket: 'kot-pos-app.firebasestorage.app',
    iosBundleId: 'com.example.kotApp',
  );
}
